[workspace]
members = [
    "debug_util/cmd", # debuger
    "libs/compiler/defs/*",
    "libs/compiler/converts/*",
    "libs/compiler/meguc_main",
    "libs/utils",
    "libs/aidan-rs",
    "cli" # cli
]
resolver = "2"

[workspace.dependencies]
anyhow = "1"