[workspace]
members = [
    "debug_util/cmd", # debuger
    "libs/compiler/defs/*",
    "libs/compiler/converts/*",
    "libs/compiler/meguc_main",
    "cli" # cli
]

[workspace.dependencies]
anyhow = "1"